export const IMAGES = {
    KAKAO_KLIP_ICON: '/images/logos/klipLogo.svg',
    KAIKAS_ICON: '/images/logos/kaikasLogo.svg',
    basicBearWhite: "static/images/basicBearWhite.png",
    planets: {
        11: "static/images/planets/11.png",
        13: "static/images/planets/13.png",
        18: "static/images/planets/18.png",
        19: "static/images/planets/19.png",
    },
    gomzPlanet: "static/images/gomzPlanet.png",
    gomz: {
        '1cut': "static/images/1cut.png",
    },
    gomz9: '/images/9.png',
    metaverse: '/videos/metaverse.mp4',
    basicBearNoBg: "/images/basicBearNoBg.png",
    betterWorldBWLogo: '/images/logos/betterWorldBWLogo.png',
    betterWorldBlueLogo: '/images/logos/betterWorldBlueLogo.png',
    gomzDAOExample: '/images/gomzDAOExample.png',
    backButton: '/images/back.png',
    characters: {
        alien: '/images/characters/alien.png',
        blue: '/images/characters/blue.png',
        brother: '/images/characters/brother.png',
        clown: '/images/characters/clown.png',
        dark: '/images/characters/dark.png',
        enchantress: '/images/characters/enchantress.png',
        footballer: '/images/characters/footballer.png',
        fromTheFuture: '/images/characters/fromTheFuture.png',
        geek: '/images/characters/geek.png',
        guy: '/images/characters/guy.png',
        irishMan: '/images/characters/irishMan.png',
        kev: '/images/characters/kev.png',
        kimono: '/images/characters/kimono.png',
        madScientist: '/images/characters/madScientist.png',
        naked: '/images/characters/naked.png',
        oldMan: '/images/characters/oldMan.png',
        pineappleHead: '/images/characters/pineappleHead.png',
        playboyGirl: '/images/characters/playboyGirl.png',
        princess: '/images/characters/princess.png',
        q: '/images/characters/q.png',
        statueOfLiberty: '/images/characters/statueOfLiberty.png',
        telekinesis: '/images/characters/telekinesis.png',
        vampire: '/images/characters/vampire.png',
        zAfro: '/images/characters/zAfro.png',
        zBangs: '/images/characters/zBangs.png',
        zBloodyLeftHead: '/images/characters/zBloodyLeftHead.png',
        zBloodyMouth: '/images/characters/zBloodyMouth.png',
        zBloodyRightHead: '/images/characters/zBloodyRightHead.png',
        zNormal: '/images/characters/zNormal.png',
        "0xb40b60001fd13767b430f8c5b212642607584c62": '/images/characters/seungan.png',
        "0xb073a6b858c70f182222702412d37810ae037ccd": '/images/characters/sehan.png',
        "0xff86c64f594ccba9335fc50043b6a85eec220323": '/images/characters/minjun.png',
        default: '/images/characters/basicBearNBg.png'
    },
}