export const IMAGES = {
    KAKAO_KLIP_ICON: '/images/logos/klipLogo.svg',
    KAIKAS_ICON: '/images/logos/kaikasLogo.svg',
    gomzAstronaut: "/images/gomzAstronaut.gif",
    metaverse: '/videos/metaverse.mp4',
    betterWorldBWLogo: '/images/logos/betterWorldBWLogo.png',
    betterWorldBlueLogo: '/images/logos/betterWorldBlueLogo.png',
    betterWorldWhiteLogo: '/images/logos/betterWorldWhiteLogo.png',
    betterWorldBlueShadowLogo: '/images/logos/betterWorldBlueShadowLogo.png',
    betterWorldFullLogo: '/images/logos/betterWorldFullLogo.png',
    betterWorldBold: '/images/logos/betterWorldBold.png',
    betterWorldWord: '/images/logos/betterWorldWord.png',
    webeDraft: '/images/webeDraft.png',
    webeDraft2: '/images/webeDraft2.png',
    webeDraft3: '/images/webeDraft3.png',
    appDraft: 'images/appDraft.png',
    appDraft2: 'images/appDraft2.png',
    appDraft3: 'images/appDraft3.png',
    appDraft4: 'images/appDraft4.png',
    gomzDAOExample: '/images/gomzDAOExample.png',
    backButton: '/images/back.png',
    betterWorldFeedExample: '/images/feed.png',
    appView: '/images/appView.png',
    connectExample: '/images/connect.png',
    downloadOnAppStore: '/images/downloadOnAppStore.png',
    downloadOnGooglePlay: '/images/downloadOnGooglePlay.png',
    characters: {
        default: '/images/characters/basicBearNBg.png'
    },
}